ZerobugPark/Streamify

Streamify.xcodeproj/project.pbxproj
Streamify/Info.plist

iOS 최소 버전 16
다크모드 미지원
세로모드 Only

feat: 프로젝트 초기 설정 #1

---

Streamify.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

feat: SPM-업데이트

---

Streamify.xcodeproj/project.pbxproj
Streamify/Core/Base/BaseViewController.swift
Streamify/Core/Base/BaseViewModel.swift
Streamify/Core/Base/ViewModelType.swift
Streamify/Core/ViewControllerType.swift

BaseViewController add
BaseViewModel add
ViewControllerType add
ViewModelType add

feat: #10베이스-뷰-컨트롤러-뷰모델-추가SPM-업데이트

---

Streamify.xcodeproj/project.pbxproj
Streamify/Core/Utilities/Designs/StreamifyColor.swift
Streamify/Core/Utilities/Designs/StreamifyFont.swift
Streamify/Core/Utilities/Designs/StreamifySymbol.swift

[ADD]
- StreamifyColor
- StreamifyFont
- StreamifySymbol
[참고사항]
시뮬레이터로 테스트 해본 결과, 폰트 사이즈가 16,14,13만 있을 경우 조금 버튼쪽에는 작아보이는 이슈가 있어어 24 폰트 사이즈 추가했습니다.

feat:#17-design-시스템-구축

---

Streamify.xcodeproj/project.pbxproj

- Coordinator 폴더 추가 완료
- Empty 파일 추가 (해당 폴더에 파일 추가하시는 분이 삭제 부탁드립니다)

feat:#19-coordinator-폴더-추가

---

Streamify.xcodeproj/project.pbxproj
Streamify/Core/Utilities/Components/VerticalListView.swift
Streamify/Feature/StorageBox/StarRatingStorage/StarRatingStorageCollectionViewCell.swift
Streamify/Feature/StorageBox/StarRatingStorage/StarRatingStorageView.swift
Streamify/Feature/StorageBox/StarRatingStorage/StarRatingStorageViewController.swift
Streamify/Feature/StorageBox/StarRatingStorage/StarRatingStorageViewModel.swift
Streamify/Feature/ViewController.swift

[파일 추가]
Component/VerticalListView : 별점 / 서치 공통 컬렉션뷰 컴포넌트 추가
Feature/StorageBox: 별점 화면 추가
[Fix]
ViewController : 컬렉션뷰 테스트 코드 추가
*공통 사용이다보니, 테스트코드 기반으로 작성되었으며, 실제 작업시 변수명 등이 수정될 수 있습니다.

feat:#25-컬렉션-뷰-컴포넌트-및-별점-화면-초안-구현

---

Streamify.xcodeproj/project.pbxproj
Streamify/Application/Model/DramaTable.swift
Streamify/Application/Services/RealmDramaRepository.swift
Streamify/Application/Services/RealmRepository.swift
Streamify/Core/Utilities/Components/ProgressBar.swift

- Realm 테이블 설계
- Repository 구성
- ProgressBar 컴포넌트 생성
```swift
owner.progressBar.progress = owner.drama.watchingProgress
```
`watchingProgress` -> 드라마 진행률 입니다!
ProgressBar의 progress속성에 진행률을 넣어주시면 됩니다~

Feature/#24 realm 테이블 및 repository 구성 progressbar 컴포넌트 생성

---

Streamify.xcodeproj/project.pbxproj
Streamify/Application/Coordinator/MainCoordinator.swift
Streamify/Application/SceneDelegate.swift
Streamify/Feature/Main/View/MainViewController.swift
Streamify/Feature/Main/View/TopRatedCell.swift
Streamify/Feature/Main/ViewModel/MainViewModel.swift

홈화면 UI 구성
Nav Bar 구성
CollectionView Component 활용하여 구성

Main 화면 UI 및 ViewModel 구성

---

Streamify.xcodeproj/project.pbxproj
Streamify/Application/SceneDelegate.swift
Streamify/Application/Services/TMDBEndpoint.swift
Streamify/Application/Services/TMDBRequest.swift
Streamify/Application/Services/TMDBResponse.swift
Streamify/Feature/Main/View/HorizontalMediaCell.swift
Streamify/Feature/Main/View/MainViewController.swift
Streamify/Feature/Main/View/TopRatedCell.swift
Streamify/Feature/Main/ViewModel/MainViewModel.swift

- UI 레이아웃에 데이터 바인딩
- 보관함 화면과 Coordinator로 연결

홈화면 데이터와 바인딩

---

Streamify.xcodeproj/project.pbxproj
Streamify/Application/Coordinator/DetailCoordintaor.swift
Streamify/Application/Coordinator/MainCoordinator.swift
Streamify/Feature/DetailDrama/View/DramaViewController.swift
Streamify/Feature/DetailDrama/ViewModel/DramaViewModel.swift
Streamify/Feature/Main/View/MainViewController.swift
Streamify/Feature/Search/View/SearchCollectionViewCell.swift
Streamify/Feature/Search/View/SearchViewController.swift

- 상세 화면에서 활용할 DetailCoordinator 생성
- 검색 화면 기본 기능 구성(서치바에 입력/엔터 시 검색 결과 Collection View와 바인딩)
- 검색 결과 cell 클릭시 해당 ID를 상세화면으로 전달 및 전환

검색화면 구성 및 DetailCoordinator 생성

---

Streamify.xcodeproj/project.pbxproj
Streamify/Application/Coordinator/MainCoordinator.swift
Streamify/Feature/StorageBox/Comment/View/CommentTableViewCell.swift
Streamify/Feature/StorageBox/Comment/View/CommentView.swift
Streamify/Feature/StorageBox/Comment/View/CommentViewController.swift
Streamify/Feature/StorageBox/Comment/ViewModel/CommentViewModel.swift
Streamify/Feature/StorageBox/StarRatingStorage/View/FilterButton.swift
Streamify/Feature/StorageBox/StarRatingStorage/View/StarRatingStorageCollectionViewCell.swift
Streamify/Feature/StorageBox/StarRatingStorage/View/StarRatingStorageViewController.swift
Streamify/Feature/StorageBox/StarRatingStorage/ViewModel/StarRatingStorageViewModel.swift
Streamify/Feature/StorageBox/Storage/View/StorageCollectionViewCell.swift
Streamify/Feature/StorageBox/Storage/View/StorageViewController.swift
Streamify/Feature/StorageBox/Storage/ViewModel/StorageViewModel.swift
Streamify/Feature/StorageBox/Storage/ViewModel/StroageStruct.swift

- 별점 필터 버튼 적용
- 코멘트 기본 화면 구성
- 코멘트 서치바 추가
- 데이터 구조 변경
기존: 
각 뷰모델에서 이미지 데이터 로드 후 셀에서 표시
변경:
스토리지 뷰모델에서 이미지데이터 모두 로드 후, 각 데이터별로 생성자를 통해 값 전달(DI)

Feature/#46 별점 필터 버튼 적용 및 코멘트 화면 구성

---

Streamify/Core/Utilities/Components/BaseImageView.swift
Streamify/Core/Utilities/Components/CompositionalListView.swift
Streamify/Feature/StorageBox/Comment/View/CommentViewController.swift
Streamify/Feature/StorageBox/StarRatingStorage/View/StarRatingStorageCollectionViewCell.swift
Streamify/Feature/StorageBox/StarRatingStorage/View/StarRatingStorageViewController.swift
Streamify/Feature/StorageBox/Storage/View/StorageCollectionViewCell.swift
Streamify/Feature/StorageBox/Storage/View/StorageViewController.swift
Streamify/Feature/StorageBox/Storage/ViewModel/StorageViewModel.swift

1. 스토리지 필터 조건 수정
2. 스토리지뷰 레이아웃 조정
3. 네비게이션 속성 추가 (AppDelegate)

Feature/#58 스로티지 필터 조건 수정 및 전체적인 UI 수정

---

Streamify/Feature/Main/View/HorizontalMediaCell.swift
Streamify/Feature/Main/View/MainViewController.swift
Streamify/Feature/Main/ViewModel/MainViewModel.swift
Streamify/Feature/Search/View/SearchViewController.swift

메인 화면 UI 및 레이아웃을 세부적으로 수정하고 cell 선택 시 세부화면으로 넘어갈 수 있도록 구성했습니다.

메인 화면 UI 레이아웃 수정

---

Streamify.xcodeproj/project.pbxproj
Streamify/Application/Coordinator/DetailCoordintaor.swift
Streamify/Application/Coordinator/MainCoordinator.swift
Streamify/Application/Model/DetailDrama.swift
Streamify/Application/Model/DramaTable.swift
Streamify/Application/Services/NotificationCenterManager.swift
Streamify/Application/Services/RealmDramaRepository.swift
Streamify/Application/Services/RealmRepository.swift
Streamify/Feature/DetailDrama/View/DramaEpisodeCell.swift
Streamify/Feature/DetailDrama/View/DramaHeaderCell.swift
Streamify/Feature/DetailDrama/View/DramaView.swift
Streamify/Feature/DetailDrama/View/DramaViewController.swift
Streamify/Feature/DetailDrama/ViewModel/DramaViewModel.swift
Streamify/Feature/DetailEpisode/View/EpisodeCell.swift
Streamify/Feature/DetailEpisode/View/EpisodeHeaderCell.swift
Streamify/Feature/DetailEpisode/View/EpisodeView.swift
Streamify/Feature/DetailEpisode/View/EpisodeViewController.swift
Streamify/Feature/DetailEpisode/ViewModel/EpisodeCellViewModel.swift
Streamify/Feature/DetailEpisode/ViewModel/EpisodeViewModel.swift

- 드라마 화면 네트워크 데이터 바인딩
- 에피소드 화면 네트워크 데이터 바인딩
- 렘 연결중

Feature/#53 상세화면 네트워크 및 렘 연결 코멘트 및 별점 구현

---

Streamify/Application/Coordinator/MainCoordinator.swift
Streamify/Application/Coordinator/OnboardingCoordinator.swift
Streamify/Application/Model/Genre.swift
Streamify/Application/SceneDelegate.swift
Streamify/Application/Services/RealmRepository.swift
Streamify/Feature/Main/View/MainViewController.swift
Streamify/Feature/Onboarding/View/GenreCell.swift
Streamify/Feature/Onboarding/View/GenreSelectionViewController.swift
Streamify/Feature/Onboarding/ViewModel/GenreSelectionViewModel.swift

온보딩 화면 버튼 버그, 온보딩 완료 후 화면 전환 버그를 픽스했습니다.

온보딩 화면 버튼 버그 및 온보딩 완료 후 화면 전환 버그 픽스

---

Streamify/Application/Coordinator/DetailCoordintaor.swift
Streamify/Application/Model/DramaTable.swift
Streamify/Core/Utilities/Components/ActionButton.swift
Streamify/Feature/DetailDrama/View/DramaEpisodeCell.swift
Streamify/Feature/DetailDrama/View/DramaViewController.swift
Streamify/Feature/DetailDrama/ViewModel/DramaViewModel.swift
Streamify/Feature/DetailEpisode/View/EpisodeButtonCell.swift
Streamify/Feature/DetailEpisode/View/EpisodeCell.swift
Streamify/Feature/DetailEpisode/View/EpisodeViewController.swift
Streamify/Feature/DetailEpisode/ViewModel/EpisodeCellViewModel.swift
Streamify/Feature/DetailEpisode/ViewModel/EpisodeViewModel.swift

fix: 렘 이슈 고침

---

Streamify.xcodeproj/project.pbxproj
Streamify/Application/Coordinator/OnboardingCoordinator.swift
Streamify/Feature/Onboarding/View/GenreCell.swift
Streamify/Feature/Onboarding/View/GenreSelectionView.swift
Streamify/Feature/Onboarding/View/GenreSelectionViewController.swift
Streamify/Feature/Onboarding/View/NameInputView.swift
Streamify/Feature/Onboarding/View/NameInputViewController.swift
Streamify/Feature/Onboarding/ViewModel/GenreSelectionViewModel.swift
Streamify/Feature/Onboarding/ViewModel/NameInputViewModel.swift
Streamify/Feature/StorageBox/Storage/ModifyUserName/View/ModifyViewController.swift

- 온보딩의 이름 입력화면, 관심 장르 선택화면에 BaseViewController/BaseViewModel을 적용시켰습니다.
- 디자인도 기존 디자인과 어울리도록 적절하게 변경하였습니다.

Refactor/#68 base 활용 리팩토링

---

Streamify/Feature/Main/ViewModel/MainViewModel.swift
Streamify/Feature/Onboarding/View/GenreSelectionView.swift

추천 컨텐츠 실제 사용자가 선택한 장르로 추천되도록 로직 추가 및 헤더 이름을 사용자 이름으로 변경했습니다.

추천 컨텐츠 실제 사용자가 선택한 장르로 추천되도록 구성

---

Streamify/Core/Utilities/Components/ActionButton.swift
Streamify/Feature/StorageBox/Storage/View/StorageCollectionViewCell.swift
Streamify/Feature/StorageBox/Storage/View/StorageViewController.swift
Streamify/Feature/StorageBox/Storage/ViewModel/StorageViewModel.swift
Streamify/Feature/StorageBox/Storage/ViewModel/StroageStruct.swift

1. 렘 테스트
2. 보고싶어요, 봤어요, 보는중입니다. 업데이트 반영

Feature/#65 렘 테스트

---

Streamify/Core/Utilities/Components/ActionButton.swift
Streamify/Feature/DetailEpisode/View/EpisodeButtonCell.swift
Streamify/Feature/DetailEpisode/View/EpisodeCell.swift
Streamify/Feature/DetailEpisode/View/EpisodeViewController.swift
Streamify/Feature/DetailEpisode/ViewModel/EpisodeCellViewModel.swift
Streamify/Feature/DetailEpisode/ViewModel/EpisodeViewModel.swift

- 체크버튼 토글 이슈 해결
- 봤어요, 보는중 UI 데이터 반영

Feature/#70 체크버튼 디버깅 및 모달

---

Streamify/Application/Model/DramaTable.swift
Streamify/Application/Services/RealmDramaRepository.swift
Streamify/Core/Utilities/Components/ProgressBar.swift
Streamify/Feature/DetailDrama/View/DramaEpisodeCell.swift
Streamify/Feature/DetailDrama/View/DramaHeaderCell.swift
Streamify/Feature/DetailDrama/View/DramaViewController.swift
Streamify/Feature/DetailDrama/ViewModel/DramaViewModel.swift
Streamify/Feature/DetailEpisode/View/EpisodeButtonCell.swift
Streamify/Feature/DetailEpisode/View/EpisodeCell.swift
Streamify/Feature/DetailEpisode/View/EpisodeHeaderCell.swift
Streamify/Feature/DetailEpisode/View/EpisodeModalViewController.swift
Streamify/Feature/DetailEpisode/View/EpisodeView.swift
Streamify/Feature/DetailEpisode/View/EpisodeViewController.swift

Feature/#77 찜 기능 추가
